version: "3.7"
services:

    mongodb:
        container_name: mongo_db
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin3231
            MONGO_INITDB_DATABASE: dogs

        volumes:
          - /var/lib/docker/volumes/mongoVolume/_data

    # populate:
    #     build: ./Base-de-datos
    #     container_name: populate.py
    #     depends_on:
    #       - "mongodb"
    #     restart: always
    #     command: ["python", "./populate.py"]
    #     volumes:
    #       - ./populate:/usr/src/populate

    mongo-express:
        container_name: dbms
        image: mongo-express
        restart: always
        ports:
            - "8082:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin3231
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin3231

